version: '3'
services:
  nginx-proxy:
    volumes:
      - ./proxy/api-nginx-config:/etc/nginx/vhost.d/api.localhost
  api:
    volumes:
      - ./api:/app
    expose:
      - "${FLASK_RUN_PORT}"
  frontend:
    volumes:
      - ./frontend:/app # Allows hot reloading code
      - /app/node_modules # Prevents above volume from
      # overwriting docker installed node_modules
      # https://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html#the-node_modules-volume-trick
    expose:
      - "${REACT_PORT}"