version: '3'
services:
  web:
    build: ./web
    environment:
      - FLASK_ENV
      - FLASK_RUN_HOST
      - FLASK_RUN_PORT
      - FLASK_APP=run.py
  frontend:
    environment:
      - REACT_PORT
      - FLASK_RUN_HOST
      - FLASK_RUN_PORT
      - HTTP_PROXY
      - REACT_APP_FLASK_RUN_HOST=${FLASK_RUN_HOST}
      - REACT_APP_FLASK_RUN_PORT=${FLASK_RUN_PORT}
    build: ./frontend