version: '3'
services:
  nginx-proxy:
    nginx-proxy:
      image: jwilder/nginx-proxy
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro

  api:
    build: ./api
    environment:
      - FLASK_ENV
      - FLASK_RUN_HOST
      - FLASK_RUN_PORT
      - FLASK_APP=run.py
  frontend:
    environment:
      - REACT_PORT
      - FLASK_RUN_HOST
      - FLASK_RUN_PORT
      - HTTP_PROXY
      - REACT_APP_FLASK_RUN_HOST=${FLASK_RUN_HOST}
      - REACT_APP_FLASK_RUN_PORT=${FLASK_RUN_PORT}
    build: ./frontend