version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  api:
    build: ./api
    environment:
      - VIRTUAL_HOST=${API_URL}
      - FLASK_ENV
      - FLASK_RUN_HOST
      - FLASK_RUN_PORT
      - FLASK_APP=run.py
  frontend:
    environment:
      - VIRTUAL_HOST=${FRONTEND_URL}
      - REACT_PORT
      - REACT_APP_API_URL=${API_URL}
    build: ./frontend