version: '3'
services:
  web:
    volumes:
      - ./web:/app
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"