version: '3'
services:
  web:
    build: ./web
    environment:
      - FLASK_ENV
      - FLASK_RUN_PORT
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
  frontend:
    environment:
      - REACT_PORT
    build: ./frontend