version: '3'
services:
  nginx-proxy:
    volumes:
      - ./proxy/api-nginx-config:/etc/nginx/vhost.d/api.localhost
  api:
    volumes:
      - ./api:/app
    expose:
      - "${FLASK_RUN_PORT}"
  frontend:
    volumes:
      - ./frontend:/app
    expose:
      - "${REACT_PORT}"